# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 21e3ac07f1fe1f7679d695762cf017392aab38a18088007a90bc8bfb548eaa088e59378b5bc3a555fc0a1ea5eb9692a76f9d7e91e8891350e9a773bf22f8154f

test:
  secret_key_base: 9d98b7ea67670fcf32abfca9939bf3bf4bdb5276590066cfe687517a8a6c97092f97465dcdc4538912470aaed5df5a702d1ecefae0e1552d23706bf77300fb72

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
